// Bringing papers up to date (daemon/lib/catchup.mjs): prompt versions, what a note says made it, and what's to do.
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const U = () => import("../daemon/lib/catchup.mjs");
const T = () => import("../daemon/lib/taxonomies.mjs");

const prompt = (over) => Object.assign({ id: "findings", title: "Findings", model: "default", effort: "high", output: "note", brief: true, body: "Summarize." }, over || {});

test("a prompt's version: its text, what it makes and its brief decide it, not its title, model or effort", async () => {
  const { promptFingerprint } = await U();
  const h = promptFingerprint(prompt());
  assert.match(h, /^[0-9a-f]{12}$/);
  assert.equal(promptFingerprint(prompt({ title: "Other", model: "claude:opus", effort: "low", body: "  Summarize.\n" })), h);
  assert.notEqual(promptFingerprint(prompt({ body: "Summarize briefly." })), h);
  assert.notEqual(promptFingerprint(prompt({ output: "concept-map" })), h);
  assert.equal(promptFingerprint(prompt({ brief: false })), h); // a note has no brief
  assert.notEqual(promptFingerprint(prompt({ output: "concept-map", brief: false })), promptFingerprint(prompt({ output: "concept-map" })));
});

test("version numbers: each new text the next one, an old text its own again; kept in a file", async () => {
  const { versionOf, versionsFor, loadVersions } = await U();
  const reg = { prompts: {} };
  assert.deepEqual([versionOf(reg, prompt()).n, versionOf(reg, prompt()).changed], [1, false]);
  assert.equal(versionOf(reg, prompt({ body: "New." })).n, 2);
  assert.equal(versionOf(reg, prompt()).n, 1); // back to the first text
  const file = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "oma-versions-")), "v.json");
  assert.equal(versionsFor([prompt()], file).get("findings").n, 1);
  assert.equal(versionsFor([prompt({ body: "New." })], file).get("findings").n, 2);
  assert.equal(loadVersions(file).prompts.findings.length, 2);
});

test("what a note says made it: the prompt, its version and hash; older notes only the title", async () => {
  const { parseGenerated } = await U();
  assert.deepEqual(parseGenerated("Generated by Claude (opus) with the “Findings” prompt, version 2 (findings@3f2a91c0b1d2), on 2026-10-04. Check quotes."),
    { promptId: "findings", hash: "3f2a91c0b1d2", n: 2, title: "Findings" });
  assert.deepEqual(parseGenerated("Generated by Claude (opus) with the “Findings” prompt on 2026-01-02."), { promptId: "", hash: "", n: 0, title: "Findings" });
  assert.deepEqual(parseGenerated(""), { promptId: "", hash: "", n: 0, title: "" });
});

test("runs: the latest per paper and prompt, from notes and artifacts; older ones stale, unknown ones left alone", async () => {
  const { promptRuns, stalePromptJobs, recentJobs, paperCount } = await U();
  const prompts = [prompt(), prompt({ id: "map", title: "Map", output: "concept-map" })];
  const gen = (v, h) => `Generated by X (y) with the “Findings” prompt, version ${v} (findings@${h}), on 2026-10-01.`;
  const notes = [
    { libraryID: 1, parentKey: "AAAAAAAA", dateAdded: "2026-01-01 00:00:00", generated: gen(1, "aaaaaaaaaaaa") },
    { libraryID: 1, parentKey: "AAAAAAAA", dateAdded: "2026-02-01 00:00:00", generated: gen(2, "bbbbbbbbbbbb") }, // its latest
    { libraryID: 1, parentKey: "BBBBBBBB", dateAdded: "2026-01-01 00:00:00", generated: gen(1, "aaaaaaaaaaaa") },
    { libraryID: 1, parentKey: "CCCCCCCC", dateAdded: "2025-01-01 00:00:00", generated: "Generated by X with the “Findings” prompt on 2025-01-01." },
    { libraryID: 1, parentKey: "", generated: gen(1, "aaaaaaaaaaaa") },
  ];
  const artifacts = [{ key: "BBBBBBBB", libraryID: 1, promptMade: { id: "map", hash: "cccccccccccc", at: "2026-03-01T00:00:00Z" } }, { key: "DDDDDDDD", libraryID: 1, promptMade: null }];
  const runs = promptRuns(notes, artifacts, prompts);
  assert.deepEqual(runs["1:AAAAAAAA"], { findings: { hash: "bbbbbbbbbbbb", at: "2026-02-01 00:00:00" } });
  assert.equal(runs["1:CCCCCCCC"].findings.hash, ""); // matched by its title
  assert.equal(runs["1:BBBBBBBB"].map.hash, "cccccccccccc");
  const versions = new Map([["findings", { n: 2, hash: "bbbbbbbbbbbb" }], ["map", { n: 1, hash: "dddddddddddd" }]]);
  const s = stalePromptJobs(runs, versions);
  assert.deepEqual(s.jobs.map((j) => [j.id, j.prompt]).sort(), [["1:BBBBBBBB", "findings"], ["1:BBBBBBBB", "map"]]);
  assert.equal(s.unknown, 1);
  assert.equal(paperCount(s.jobs), 1);
  // the last days: never run, or an older version; a run before versions were kept counts as done
  const papers = [{ key: "AAAAAAAA", libraryID: 1, title: "A" }, { key: "BBBBBBBB", libraryID: 1, title: "B" }, { key: "CCCCCCCC", libraryID: 1, title: "C" }, { key: "EEEEEEEE", libraryID: 1, title: "E" }];
  const jobs = recentJobs(papers, { prompts: ["findings"], runs, versions, extract: true, textless: ["1:EEEEEEEE"] });
  assert.deepEqual(jobs.map((j) => [j.id, j.op]), [["1:BBBBBBBB", "prompt"], ["1:EEEEEEEE", "extract"], ["1:EEEEEEEE", "prompt"]]);
});

test("taxonomies: papers tagged by an older version, and the last days' papers never tagged (by the ones they miss)", async () => {
  const { staleTaxonomyJobs, recentJobs } = await U();
  const { fingerprint } = await T();
  const a = { id: "method", prefix: "method/", kind: "one", question: "q", labels: [{ name: "survey", definition: "" }] };
  const b = { id: "type", prefix: "type/", kind: "one", question: "q", labels: [{ name: "case", definition: "" }] };
  const store = { papers: {
    "1:AAAAAAAA": { taxonomies: { method: { hash: fingerprint(a), probs: {} }, type: { hash: fingerprint(b), probs: {} } } },
    "1:BBBBBBBB": { taxonomies: { method: { hash: "old", probs: {} }, type: { hash: fingerprint(b), probs: {} } } },
  } };
  assert.deepEqual(staleTaxonomyJobs(store, [a, b]), [{ id: "1:BBBBBBBB", op: "classify", only: ["method"] }]);
  const papers = [{ key: "AAAAAAAA", libraryID: 1 }, { key: "BBBBBBBB", libraryID: 1 }, { key: "CCCCCCCC", libraryID: 1 }];
  const jobs = recentJobs(papers, { tag: true, store, taxonomies: [a, b] });
  assert.deepEqual(jobs.map((j) => [j.id, j.only || "all"]), [["1:BBBBBBBB", ["method"]], ["1:CCCCCCCC", "all"]]);
  assert.deepEqual(recentJobs(papers, { tag: false, store, taxonomies: [a, b] }), []);
});
