// Bringing papers up to date (the launcher's Settings › Defaults › New papers): which papers a prompt ran on with an
// older version of it, which a taxonomy tagged with an older version of it, and what papers added in the last days
// still miss. Pure but for the versions file (node-tested).
//
// A prompt's version: what decides what it writes (its text, what it makes, whether an artifact is planned first),
// not its title, model or effort. Each new text gets the next number (versions file: { prompts: { id: [{ n, hash,
// at }] } }); a note says both, in its title ("Findings v2: …") and its last line ("… prompt, version 2
// (findings@3f2a91c0b1d2) …"): the hash, synced with the note, is what tells an older version apart on any machine.
import { readFileSync, writeFileSync, mkdirSync, renameSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, dirname } from "node:path";
import { homedir } from "node:os";
import { staleTaxonomies } from "./taxonomies.mjs";

export function promptFingerprint(p) {
  const what = { body: String(p.body || "").trim(), output: p.output || "note", brief: p.output && p.output !== "note" ? p.brief !== false : true };
  return createHash("sha1").update(JSON.stringify(what)).digest("hex").slice(0, 12);
}

export function versionsPath(env = process.env) {
  return join(env.XDG_STATE_HOME || join(env.HOME || homedir(), ".local", "state"), "oma-zotero", "prompt-versions.json");
}

export function loadVersions(path = versionsPath()) {
  try {
    const j = JSON.parse(readFileSync(path, "utf8"));
    return j && typeof j.prompts === "object" && j.prompts ? j : { prompts: {} };
  } catch {
    return { prompts: {} };
  }
}

export function saveVersions(reg, path = versionsPath()) {
  mkdirSync(dirname(path), { recursive: true });
  const tmp = path + ".tmp";
  writeFileSync(tmp, JSON.stringify(reg, null, 2) + "\n");
  renameSync(tmp, path);
}

// The prompt's version number, its text seen for the first time: the next one (reg changes; changed says so).
// → { n, hash, changed }
export function versionOf(reg, p, now = new Date()) {
  const hash = promptFingerprint(p);
  const list = reg.prompts[p.id] || (reg.prompts[p.id] = []);
  const known = list.find((v) => v.hash === hash);
  if (known) return { n: known.n, hash, changed: false };
  const n = list.reduce((m, v) => Math.max(m, v.n), 0) + 1;
  list.push({ n, hash, at: now.toISOString() });
  return { n, hash, changed: true };
}

// Every prompt's version, saved when one is new. → Map id → { n, hash }
export function versionsFor(prompts, path = versionsPath()) {
  const reg = loadVersions(path);
  const out = new Map();
  let changed = false;
  for (const p of prompts) {
    const v = versionOf(reg, p);
    changed = changed || v.changed;
    out.set(p.id, { n: v.n, hash: v.hash });
  }
  if (changed) saveVersions(reg, path);
  return out;
}

// What a prompt's note says made it (its "Generated by …" line): { promptId, hash, n, title }; notes from before
// versions were kept name only the prompt's title (hash "").
export function parseGenerated(line) {
  const s = String(line || "");
  const title = (/with the “([^”]*)” prompt/.exec(s) || [])[1] || "";
  const m = /version (\d+) \(([a-z0-9][a-z0-9-]{0,80})@([0-9a-f]{12})\)/.exec(s);
  return m ? { promptId: m[2], hash: m[3], n: Number(m[1]), title } : { promptId: "", hash: "", n: 0, title };
}

// The latest run of each prompt on each paper, from its notes ([{ libraryID, parentKey, dateAdded, generated }],
// the bridge's /notes/by-prompt) and its artifacts' prompt-made versions ([{ key, libraryID, promptMade: { id,
// hash, at } }]). An older note without a version is matched to a prompt by its title (hash "": unknown).
// → { "lib:key": { promptId: { hash, at } } }
export function promptRuns(notes, artifacts, prompts) {
  const byTitle = new Map(prompts.map((p) => [p.title, p.id]));
  const runs = {};
  const put = (paper, id, hash, at) => {
    if (!id) return;
    const r = runs[paper] || (runs[paper] = {});
    if (!r[id] || String(at) > String(r[id].at)) r[id] = { hash, at: String(at || "") };
  };
  for (const n of notes || []) {
    if (!n.parentKey) continue;
    const g = parseGenerated(n.generated);
    put((Number(n.libraryID) || 1) + ":" + n.parentKey, g.promptId || byTitle.get(g.title) || "", g.hash, n.dateAdded);
  }
  for (const a of artifacts || []) {
    if (a.promptMade) put((Number(a.libraryID) || 1) + ":" + a.key, a.promptMade.id, a.promptMade.hash || "", a.promptMade.at);
  }
  return runs;
}

// The runs of a prompt with an older version of it (unknown: runs from before versions were kept, left alone).
// → { jobs: [{ id: "lib:key", op: "prompt", prompt }], unknown }
export function stalePromptJobs(runs, versions) {
  const jobs = [];
  let unknown = 0;
  for (const [paper, byPrompt] of Object.entries(runs)) {
    for (const [id, r] of Object.entries(byPrompt)) {
      const v = versions.get(id);
      if (!v) continue; // a prompt since deleted
      if (!r.hash) unknown++;
      else if (r.hash !== v.hash) jobs.push({ id: paper, op: "prompt", prompt: id });
    }
  }
  return { jobs, unknown };
}

// The papers a taxonomy tagged with an older version of it (the store's; never-tagged papers aren't here: the
// recent days catch them). → [{ id, op: "classify", only }]
export function staleTaxonomyJobs(store, taxonomies) {
  const jobs = [];
  for (const [id, e] of Object.entries((store && store.papers) || {})) {
    const only = staleTaxonomies(e, taxonomies);
    if (only.length) jobs.push({ id, op: "classify", only });
  }
  return jobs;
}

// What papers added lately (papers: [{ key, libraryID, title }], newest first) still miss, paper by paper: its text
// (textless: the ones with a PDF and no text, when extract), its taxonomies (when tag: never tagged, or by an older
// version), each prompt it never ran on or ran on with an older version. → [{ id, op, prompt?, only?, title }]
export function recentJobs(papers, { textless = [], extract = false, tag = false, store = null, taxonomies = [], prompts = [], runs = {}, versions = new Map() } = {}) {
  const noText = new Set(textless);
  const jobs = [];
  for (const p of papers || []) {
    const id = (Number(p.libraryID) || 1) + ":" + p.key;
    const title = p.title || "";
    if (extract && noText.has(id)) jobs.push({ id, op: "extract", title });
    if (tag && taxonomies.length) {
      const only = staleTaxonomies(store && store.papers ? store.papers[id] : undefined, taxonomies);
      if (only.length) jobs.push(Object.assign({ id, op: "classify", title }, only.length < taxonomies.length ? { only } : {}));
    }
    for (const pid of prompts) {
      const v = versions.get(pid);
      if (!v) continue;
      const r = (runs[id] || {})[pid];
      if (!r || (r.hash && r.hash !== v.hash)) jobs.push({ id, op: "prompt", prompt: pid, title });
    }
  }
  return jobs;
}

// How many papers a job list touches.
export function paperCount(jobs) {
  return new Set((jobs || []).map((j) => j.id)).size;
}
