#!/bin/bash
# Download the journal rankings and write zotero-bridge/lib/rankingsData.js:
#   AJG 2024 (the "ABS list", Chartered ABS Academic Journal Guide: ISSNs, field, 1–4*),
#   FT50 (Financial Times research list) and UTD24 (UT Dallas list): journal titles.
# Snapshots from github.com/wosaide/wosaide-journal-lists (LIST/), which tracks the
# official pages; pass another raw base URL as $1 to use a different copy.
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
BASE=${1:-https://raw.githubusercontent.com/wosaide/wosaide-journal-lists/HEAD/LIST}
OUT="$ROOT/zotero-bridge/lib/rankingsData.js"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

for f in AJG2024 FT50 UTD24; do
  curl -sfL --retry 3 "$BASE/$f.csv" -o "$tmp/$f.csv" || { echo "update-rankings: couldn't download $f.csv" >&2; exit 1; }
done

node - "$tmp" "$OUT" "$BASE" <<'JS'
const fs = require("fs");
const [dir, out, base] = process.argv.slice(2);
// Minimal RFC 4180 CSV parser (quoted fields, doubled quotes, BOM).
function parse(text) {
  const rows = [];
  let row = [], field = "", q = false;
  text = text.replace(/^﻿/, "");
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') q = false;
      else field += c;
    } else if (c === '"') q = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(field); field = "";
      if (row.some((x) => x !== "")) rows.push(row);
      row = [];
    } else field += c;
  }
  if (field !== "" || row.length) { row.push(field); rows.push(row); }
  const [head, ...body] = rows;
  return body.map((r) => Object.fromEntries(head.map((h, i) => [h.trim(), (r[i] || "").trim()])));
}
const read = (f) => parse(fs.readFileSync(`${dir}/${f}.csv`, "utf8"));
const ajg = read("AJG2024").map((r) => [r["Print ISSN"], r["E-ISSN"], r["Journal Title"], r["Field"], r["AJG 2024"]]).filter((r) => r[2] && r[4]);
const titles = (f) => read(f).map((r) => r["Journal title"] || r["Journal Title"]).filter(Boolean);
const ft50 = titles("FT50"), utd24 = titles("UTD24");
if (ajg.length < 1500 || ft50.length !== 50 || utd24.length !== 24) throw new Error(`unexpected sizes: AJG ${ajg.length}, FT50 ${ft50.length}, UTD24 ${utd24.length}`);
const data = { source: base, fetched: new Date().toISOString().slice(0, 10), ajgEdition: "AJG 2024", ajg, ft50, utd24 };
fs.writeFileSync(out, `/* Generated by scripts/update-rankings.sh: do not edit. Journal rankings: AJG 2024 (Chartered ABS),
 * FT50 and UTD24. Source: ${base} (${data.fetched}). */
var OMA_RANKINGS_DATA = ${JSON.stringify(data)};
`);
console.log(`wrote ${out}: AJG ${ajg.length}, FT50 ${ft50.length}, UTD24 ${utd24.length}`);
JS
